---
title: "MySQL demo"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DBI)
# connect to local docker db
db <- dbConnect(RMySQL::MySQL(), dbname = "test", "root",
                Sys.getenv('DOCKER_MYSQL_PW'),
                host = "127.0.0.1", port = 32770)
```

## Basic Queries

```{sql, connection=db}
SELECT
    id,
    country
FROM
    user_country
LIMIT 10
```

```{sql, connection=db}
SELECT
    id,
    country
FROM
    user_country
WHERE
    country = 'US'
LIMIT 10
```

```{sql, connection=db}
SELECT
    country,
    COUNT(DISTINCT id) AS num_users
FROM
    user_country
GROUP BY
    country
ORDER BY
    num_users DESC
```

```{sql, connection=db}
SELECT
    id,
    activity
FROM
    user_activity
LIMIT 10
```

```{sql, connection=db}
SELECT
    ua.id,
    ua.activity,
    uc.country
FROM
    user_activity ua
LEFT OUTER JOIN
    user_country uc
ON
    ua.id = uc.id
LIMIT 10
```

```{sql, connection=db}
SELECT
    uc.country,
    MIN(ua.activity) AS min_activity,
    MAX(ua.activity) AS max_activity,
    AVG(ua.activity) AS mean_activity
FROM
    user_activity ua
LEFT OUTER JOIN
    user_country uc
ON
    ua.id = uc.id
GROUP BY
    uc.country
ORDER BY
    mean_activity DESC
```

```{sql, connection=db}
SELECT
    id,
    plan
FROM
    user_plan
LIMIT 10
```

```{sql, connection=db}
SELECT
    plan,
    COUNT(DISTINCT id) AS num_users
FROM
    user_plan
GROUP BY
    plan
ORDER BY
    num_users DESC
```

```{sql, connection=db}
SELECT
    up.plan,
    MIN(ua.activity) AS min_activity,
    MAX(ua.activity) AS max_activity,
    AVG(ua.activity) AS mean_activity
FROM
    user_activity ua
LEFT OUTER JOIN
    user_plan up
ON
    ua.id = up.id
GROUP BY
    up.plan
ORDER BY
    mean_activity DESC
```

```{sql, connection=db, include = F, output.var="df_from_query"}
SELECT
    ua.id,
    ua.activity,
    uc.country,
    up.plan
FROM
    user_activity ua, user_country uc, user_plan up
WHERE
    ua.id = uc.id
AND
    ua.id = up.id
```

## Visualize in R using ggplot

```{r}
ggplot(df_from_query, aes(plan, activity, fill = plan)) +
    geom_violin(draw_quantiles = c(0.5), adjust = 1.0) +
    ggthemes::theme_few()
```

```{r}
ggplot(df_from_query, aes(plan, activity, fill = plan)) +
    geom_violin(draw_quantiles = c(0.5), adjust = 1.0) +
    facet_wrap(~country) +
    ggthemes::theme_few()
```
